In [2]:
# Preparacion

import matplotlib
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Carga de la tabla drivers

drivers = pd.read_csv(
    "../data/drivers.csv",
    sep=",",
    thousands=None,
    decimal=".",
)
drivers.head()

,driverId,name,ssn,location,certified,wage-plan
0,10,George Vetticaden,621011971,244-4532 Nulla Rd.,N,miles
1,11,Jamie Engesser,262112338,366-4125 Ac Street,N,miles
2,12,Paul Coddin,198041975,Ap #622-957 Risus. Street,Y,hours
3,13,Joe Niemiec,139907145,2071 Hendrerit. Ave,Y,hours
4,14,Adis Cesir,820812209,Ap #810-1228 In St.,Y,hours

In [4]:
# Carga de la tabla timesheet

timesheet = pd.read_csv(
    "../data/timesheet.csv",
    sep=",",
    thousands=None,
    decimal=".",
)
timesheet.head()

   driverId  week  hours-logged  miles-logged
0        10     1            70          3300
1        10     2            70          3300
2        10     3            60          2800
3        10     4            70          3100
4        10     5            70          3200

In [5]:
# Media de las horas y las millas de cada conductor

mean_timesheet = timesheet.groupby("driverId").mean()
mean_timesheet.head()

          week  hours-logged  miles-logged
driverId
10        26.5     62.153846   2829.807692
11        26.5     70.038462   3448.076923
12        26.5     50.750000   2614.653846
13        26.5     52.442308   2579.346154
14        26.5     53.480769   2627.384615